//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_shoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public long orderId { get; set; }
        public string articleNumber { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime deliveredAt { get; set; }
        public long addressId { get; set; }
        public long userId { get; set; }
        public long code { get; set; }
        public string status { get; set; }
    
        public virtual address address { get; set; }
        public virtual user user { get; set; }
    }
}
