//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_shoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public long productId { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public long deliveryId { get; set; }
        public long manufacturerId { get; set; }
        public long categoryId { get; set; }
        public long discount { get; set; }
        public long stock { get; set; }
        public string description { get; set; }
    
        public virtual category category { get; set; }
        public virtual deliver deliver { get; set; }
        public virtual manufacturer manufacturer { get; set; }
    }
}
