//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_shoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_roles
    {
        public long userId { get; set; }
        public long roleId { get; set; }
    
        public virtual role role { get; set; }
        public virtual user user { get; set; }
    }
}
